-- DataWarehouse-Schema fuer Oliver (Phase 3, 08.09.2026).
--
-- Zwei Schemas in EINER Datenbank. Getrennt, damit die Rollen sie
-- verschieden behandeln koennen (siehe 02-rollen.sh): coldmail_sync darf
-- kern umschreiben, historie aber nur lesen und anhaengen. In derselben
-- Datenbank, weil Postgres ueber zwei Datenbanken nicht joinen kann und
-- Oliver Firma und Historie zusammen sehen will.
--
-- Dieselbe Trennung wie in SQLite, aus demselben Grund:
--     kern      ist ein Spiegel - jederzeit aus master.db neu baubar
--     historie  ist es NICHT - ein verlorenes Opt-Out ist verloren
--
-- Laeuft nur bei leerem Volume (docker-entrypoint-initdb.d). Zum
-- Neueinspielen: docker compose ... down -v && ... up -d

BEGIN;

CREATE SCHEMA kern;
CREATE SCHEMA historie;


-- --------------------------------------------------------- schema_version
--
-- Die Skripte in /docker-entrypoint-initdb.d laufen NUR beim allerersten
-- Start mit leerem Volume. Auf dem Server wird die erste Schema-Aenderung
-- also ein ALTER von Hand sein - ohne diese Tabelle bliebe davon keine
-- Spur, und niemand koennte einer Datenbank ansehen, welchen Stand sie
-- hat. Jede Migration haengt hier eine Zeile an; der aktuelle Stand ist
-- MAX(version). (Vorgabe Dafina, 08.09.2026)

CREATE TABLE public.schema_version (
    version       integer PRIMARY KEY,
    angewendet_am timestamptz NOT NULL DEFAULT now(),
    notiz         text NOT NULL
);

INSERT INTO public.schema_version (version, notiz) VALUES
    (1, 'Phase 3: kern + historie, Rollen coldmail_sync/coldmail_read');

COMMENT ON SCHEMA kern IS
    'Spiegel von master.db - jederzeit neu baubar';
COMMENT ON SCHEMA historie IS
    'Ereignisse - NICHT wiederherstellbar, siehe Rechte in 02-rollen.sh';


-- ------------------------------------------------------------------ kern

CREATE TABLE kern.firma (
    -- Kommt aus stamm.db. KEIN DEFAULT, KEINE Identity: Postgres darf
    -- niemals selbst eine ID vergeben, sonst gaebe es zwei Stellen, die
    -- IDs erzeugen, und nach der ersten Wiederherstellung zwei
    -- verschiedene Wahrheiten darueber, welche Firma welche ist.
    firma_uid   text PRIMARY KEY,

    -- Der Schluessel aus master.db. Absichtlich NICHT unique: nachdem
    -- zwei Firmen per set_alias zusammengelegt wurden, zeigen zwei
    -- kennungen auf dieselbe firma_uid, und diese Zeile traegt die des
    -- ueberlebenden Satzes.
    kennung     text NOT NULL,

    name        text,
    domain      text,
    website     text,
    strasse     text,
    plz         text,
    ort         text,
    bundesland  text,
    land        text DEFAULT 'Deutschland',
    telefon     text,
    email_allgemein text,

    sektor      text,
    keywords    text,
    beschreibung text,
    mitarbeiter text,
    ceo_owner   text,

    offers_automation_services text DEFAULT 'not_checked',
    automation_check_reason    text,
    automation_checked_at      text,

    campaign_eligible   boolean,
    ineligibility_reason text,
    completeness        integer,

    -- Wird eine Firma per stamm_db.set_alias() zusammengelegt,
    -- verschwindet ihre uid aus der Quelle. Die Zeile wird dann NICHT
    -- geloescht, sondern zeigt hierhin auf die ueberlebende uid.
    -- Loeschen wuerde die Spur nehmen: die Historie dieser Firma
    -- verwiese auf eine uid, die es nicht mehr gibt, und alte Berichte
    -- liessen sich nicht mehr lesen. (Vorgabe Dafina, 08.09.2026 -
    -- bewusst jetzt in der Schema-Phase, nicht spaeter im Sync.)
    zusammengelegt_in text
        REFERENCES kern.firma(firma_uid) ON DELETE RESTRICT,

    created_at       timestamptz,
    updated_at       timestamptz,
    last_enriched_at text,
    -- Wann der Sync diese Zeile zuletzt angefasst hat. Gehoert dem
    -- Spiegel, nicht der Quelle.
    synced_at        timestamptz NOT NULL DEFAULT now(),

    -- Eine Firma, die in sich selbst zusammengelegt ist, waere eine
    -- Schleife: wer ihr folgt, kommt nie an.
    CONSTRAINT firma_nicht_in_sich_selbst
        CHECK (zusammengelegt_in IS NULL OR zusammengelegt_in <> firma_uid)
);

COMMENT ON COLUMN kern.firma.firma_uid IS
    'Aus stamm.db. Postgres erzeugt diese ID nie selbst.';
COMMENT ON COLUMN kern.firma.zusammengelegt_in IS
    'Gesetzt, wenn diese Firma per set_alias zusammengelegt wurde: '
    'zeigt auf die ueberlebende firma_uid. Zeile bleibt stehen.';

CREATE INDEX firma_kennung_idx           ON kern.firma(kennung);
CREATE INDEX firma_zusammengelegt_in_idx ON kern.firma(zusammengelegt_in)
    WHERE zusammengelegt_in IS NOT NULL;
CREATE INDEX firma_plz_idx               ON kern.firma(plz);


CREATE TABLE kern.entscheider (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- CASCADE ist hier richtig: Entscheider sind abgeleitete Daten und
    -- kommen beim naechsten Sync aus master.db zurueck.
    firma_uid  text NOT NULL
        REFERENCES kern.firma(firma_uid) ON DELETE CASCADE,
    name       text,
    vorname    text,
    nachname   text,
    rolle      text,
    email      text,
    email_art  text,
    telefon    text,
    linkedin   text,
    quelle     text,
    status     text,
    bereich    text,
    created_at timestamptz,
    synced_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX entscheider_firma_idx ON kern.entscheider(firma_uid);
CREATE INDEX entscheider_email_idx ON kern.entscheider(email)
    WHERE email IS NOT NULL AND email <> '';


CREATE TABLE kern.firma_quelle (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firma_uid    text NOT NULL
        REFERENCES kern.firma(firma_uid) ON DELETE CASCADE,
    provider     text,
    herkunft     text,
    collected_at text,
    felder       jsonb,
    synced_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX firma_quelle_firma_idx ON kern.firma_quelle(firma_uid);


-- -------------------------------------------------------------- historie
--
-- Alle drei zeigen mit ON DELETE RESTRICT auf kern.firma. Das ist kein
-- Formalismus: solange Historie an einer Firma haengt, laesst die
-- Datenbank das Loeschen der Firma nicht zu. Ein Fehler im Sync kann
-- einen Widerspruch damit nicht ueber den Umweg "Firma weg" wegraeumen.
--
-- firma_uid ist in ALLEN DREI absichtlich NULLABLE (Vorgabe Dafina,
-- 08.09.2026). historie.db ist ueber kennung geschluesselt, unabhaengig
-- von master.db: ein Opt-Out kann zu einer Firma gehoeren, die heute
-- nicht mehr in master steht, und der Fall "nur E-Mail" hat kennung='',
-- da gibt es gar keine uid. Waere die Spalte NOT NULL, koennte der Sync
-- solche Zeilen nicht einfuegen - das Opt-Out ginge dann nicht durch ein
-- DELETE verloren, sondern durch ein INSERT, das scheitert. Und weil der
-- Sync mit ON CONFLICT DO NOTHING arbeitet, faellt das womoeglich
-- niemandem auf. Ein stiller Verlust ist der schlimmste.
--
-- Darum stehen die UNIQUE-Bedingungen auch auf NULLS NOT DISTINCT: sonst
-- waere derselbe Eintrag ohne Firma bei jedem Lauf eine neue Zeile, weil
-- NULL <> NULL gilt.

CREATE TABLE historie.kontakt (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firma_uid     text
        REFERENCES kern.firma(firma_uid) ON DELETE RESTRICT,
    person_email  text NOT NULL DEFAULT '',

    -- KEINE Grenze 1-3. In SQLite gilt sie weiter und bleibt
    -- unangetastet; hier wird JEDER Versuch gespeichert. Die Ansicht der
    -- Phase 4 holt die ersten drei heraus. Eine Grenze in der Ablage
    -- wuerde den vierten Kontakt verlieren statt ihn auszublenden - und
    -- verloren heisst hier wirklich verloren. (Vorgabe Dafina 08.09.2026)
    nummer        integer NOT NULL,

    produkt        text,
    durch_wen      text,
    weg            text,
    resultat       text,
    datum          date NOT NULL,
    absender_email text,
    erfasst_am     timestamptz NOT NULL DEFAULT now(),

    -- Wie in SQLite: derselbe Versuch bleibt ein Eintrag, damit ein
    -- Sync zweimal laufen darf.
    CONSTRAINT kontakt_einmalig
        UNIQUE NULLS NOT DISTINCT (firma_uid, person_email, nummer)
);

COMMENT ON COLUMN historie.kontakt.nummer IS
    'Jede Nummer erlaubt - absichtlich ohne Grenze 1-3.';

CREATE INDEX kontakt_firma_idx ON historie.kontakt(firma_uid);


CREATE TABLE historie.uebergabe (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firma_uid      text
        REFERENCES kern.firma(firma_uid) ON DELETE RESTRICT,
    name           text NOT NULL,
    art_der_person text,
    datum          date NOT NULL,
    notiz          text,
    erfasst_am     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uebergabe_einmalig
        UNIQUE NULLS NOT DISTINCT (firma_uid, name, datum)
);

CREATE INDEX uebergabe_firma_idx ON historie.uebergabe(firma_uid);


CREATE TABLE historie.opt_out (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Darf leer sein: ein Widerspruch kann eine einzelne Person
    -- betreffen, ohne dass die Firma bekannt ist.
    firma_uid  text
        REFERENCES kern.firma(firma_uid) ON DELETE RESTRICT,
    email      text NOT NULL DEFAULT '',
    datum      date NOT NULL,
    weg        text,
    notiz      text,
    erfasst_am timestamptz NOT NULL DEFAULT now(),

    -- Ein Widerspruch ohne Firma UND ohne Adresse waere ein Eintrag, den
    -- niemand zuordnen kann - also einer, der niemanden schuetzt.
    CONSTRAINT opt_out_braucht_firma_oder_email
        CHECK (firma_uid IS NOT NULL OR email <> ''),

    -- NULLS NOT DISTINCT (Postgres 15+): sonst waeren zwei Widersprueche
    -- derselben Adresse ohne Firma zwei Zeilen, weil NULL <> NULL.
    CONSTRAINT opt_out_einmalig UNIQUE NULLS NOT DISTINCT (firma_uid, email)
);

CREATE INDEX opt_out_firma_idx ON historie.opt_out(firma_uid);
CREATE INDEX opt_out_email_idx ON historie.opt_out(email) WHERE email <> '';

COMMIT;
